package com.setis.estacionamento.exception;

public enum CodigoErro {
    // 400
    VALIDACAO,
    CORPO_INVALIDO,
    PARAMETRO_INVALIDO,
    PARAMETRO_OBRIGATORIO_AUSENTE,
    STATUS_NAO_PERMITIDO,
    ENTRADA_FUTURA,
    CLIENTE_OBRIGATORIO,
    CLIENTE_NAO_PERMITIDO,

    // 404
    RECURSO_NAO_ENCONTRADO,

    // 409
    CODIGO_VAGA_DUPLICADO,
    VAGA_OCUPADA,
    DOCUMENTO_DUPLICADO,
    VAGA_INDISPONIVEL,
    TICKET_ABERTO_EXISTENTE,
    TICKET_NAO_ABERTO,

    // 422
    VAGA_INCOMPATIVEL,
    SAIDA_ANTERIOR_ENTRADA,

    // Misc
    ERRO_INTERNO,
    METODO_NAO_SUPORTADO,
    MIDIA_NAO_SUPORTADA
}
